name: vale-basic
on: [pull_request, workflow_dispatch]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-22.04
    steps:
      - name: Install styles
        run: |
          set -eu
          "$GITHUB_ACTION_PATH/install.sh"
        shell: sh
        env:
        TEMPDIR: ${{ runner.temp }}
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: ./docs
          fail_on_error: true