name: vale-basic
on: [pull_request, workflow_dispatch]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: /docs
          fail_on_error: true