name: vale-basic
on: [pull_request, workflow_dispatch]

jobs:
  vale:
    name: Style checker
    runs-on: ubuntu-22.04
    defaults:
        run:
            shell: bash
            working-directory: .
    steps:
        - name: Checkout repo to runner
          uses: actions/checkout@v3
        - name: Install styles
          run: |
            set -eu
            echo ${{ github.action_path }}
            mkdir -p .github/styles/Canonical
            cp styles/*.yml .github/styles/Canonical
            cp -f styles/vale.ini.runner .vale.ini
        - name: Run Vale tests
          uses: errata-ai/vale-action@reviewdog
          with:
            files: ./docs
            fail_on_error: true